version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - adk
  - chatmessage
  - entgo
  - entsql
  - godotenv
  - gomnd
  - hnsw
  - jieba
  - joho
  - lmittmann
  - luoling
  - mindwave
  - nekomeowww
  - Nillable
  - nolint
  - pgvector
  - promauto
  - runewidth
  - samber
  - sashabaranov
  - sourcegraph
  - tablewriter
  - tabw
ignoreWords: []
import: []
