version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - adk
  - entgo
  - entsql
  - godotenv
  - hnsw
  - jieba
  - lmittmann
  - luoling
  - nekomeowww
  - Nillable
  - pgvector
  - samber
ignoreWords: []
import: []
